backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "assets/img/"
public_folder: "img"

collections:
  - name: "post"
    label: "Post"
    folder: "content/articles"
    create: true
    fields:
        {label: "Title", name: "title", widget: "string"}
        {label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
        {label: "Author", name: "author", widget: "string"}
        {label: "Image", name: "image", widget: "image"}
        {label: "Caption", name: "caption", widget: "string"}
        {label: "Show Date", name: "showthedate", widget: "boolean", default: true}
        {label: "Body", name: "body", widget: "markdown"}